version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:15"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-scripts
    versions:
    - 4.0.3
  - dependency-name: node-sass
    versions:
    - 5.0.0
  - dependency-name: ini
    versions:
    - 1.3.8
